### PR TITLE
Add contribute

### PR DESCRIPTION
**Pull request by EssamWisam**
image

In response to #228 it links to the relevant part of the README. Need to deploy after merging.

CC @ablaom

### CODE REVIEW

**Comment by EssamWisam** [comment]
Contribute is in purple bubble because mouse was over it; now I am seriously if I should rather permanently leave it like that so it grabs more attention xD.

**Comment by ablaom** [comment]
> if I should rather permanently leave it like that so it grabs more attention xD.

Nah. That's probably overkill.

**Comment by ablaom** [comment]
Do you remove the old link "Willing to contribute? Consider checking our [repository](https://github.com/JuliaAI/DataScienceTutorials.jl) on Github." - I couldn't see that in the changes.

**Comment by EssamWisam** [comment]
Didn't will add a commit.

**Review by ablaom — APPROVED** [review]
Looks good to go, thank you 🙏🏾

**Pull request merged**
